### PR TITLE
feat(experimental): Add support for using a private S3 bucket

### PR DESCRIPTION
**Pull request by JakePartusch**
TODO:

- [x] Put behind opt-in __experimental feature flag
- [x] Add documentation

### CODE REVIEW

**Comment by damc-dev** [comment]
Hey @JakePartusch, I have a need for deploying a static site without opening public access to the S3 bucket and this change seems to fit my needs perfectly.  

Is there any way I can help get this change merged into main?

**Comment by JakePartusch** [comment]
Hey @damc-dev, I didn't end up merging because of the issue here: https://github.com/JakePartusch/serverlessui/discussions/26#discussioncomment-459506

I wasn't able to find a good workaround other than deploying an Edge Lambda... And the Edge lambda would be tricky because it would need to make some assumptions about how the routing in the app would work 😕

**Comment by damc-dev** [comment]
So I was able to get it working with a CloudFront function in my fork [serverless-ui.construct.ts#L171](https://github.com/damc-dev/serverlessui/blob/feature/oai-private-s3-david/packages/construct/src/serverless-ui.construct.ts#L171) in a pretty generic way that works for both of your example applications.

simple+api: [Site](https://d3vnoacuy80hz2.cloudfront.net/) [CloudFront to API](https://d3vnoacuy80hz2.cloudfront.net/api/hello)

gatsby: [Site](https://d2odexxcb27g57.cloudfront.net/)

I am sure there are other cases that I am missing, would you be able to elaborate on the cases where this assumption wouldn't work?

**Comment by JakePartusch** [comment]
Yeah @damc-dev , I should've been more specific about the problem that I've seen when using OAI.

For example:
- Navigate to your demo website -> https://d2odexxcb27g57.cloudfront.net/
- Click on "Go to Page 2"
- Which will route you to: https://d2odexxcb27g57.cloudfront.net/page-2
- Refresh or go directly to that link in a new tab
- You get a fun 403 error

As far as I understand, this happens because page-2 is not an object in the bucket, as the object is actually /page-2/index.html. Typical public S3 websites are smart enough to figure this out, but OAI breaks it 😕. So the way that I would normally go about fixing that is to use an Edge lambda to reroute the path to /page-2/index.html if the resource receives an error on the initial route.

**Comment by damc-dev** [comment]
Interesting, I had no idea that Gatsby routing compensated for that, but would error when navigating there directly.

I updated the CloudFront function to perform the same action that is done by default in S3 (copied from [github.com/aws-samples/amazon-cloudfront-functions/url-rewrite-single-page-apps](https://github.com/aws-samples/amazon-cloudfront-functions/tree/main/url-rewrite-single-page-apps))

I think it should solve the problem!

updated simple+api: [Site](https://d1kfhygvgg4tdm.cloudfront.net/) | [CloudFront to API](https://d1kfhygvgg4tdm.cloudfront.net/api/hello)

updated gatsby: [Site](https://d2y1cbz0r0noul.cloudfront.net/)

**Comment by damc-dev** [comment]
I created a PR  [https://github.com/JakePartusch/serverlessui/pull/38](https://github.com/JakePartusch/serverlessui/pull/38) to update your feature branch, if you would prefer the PR request was against main let me know!

**Comment by JakePartusch** [comment]
Thanks, @damc-dev! I'm thinking about putting this behind a feature flag for now... Also, it looks like I have some conflicts to resolve. Hopefully I can get this updated over the weekend. Thanks for your help and feedback!

**Comment by damc-dev** [comment]
Yeah I had to update to the latest CDK to support deploying CloudFront functions, in hindsight a separate PR to just update the CDK might have been a good idea.  Sorry for dumping the extra integration work in your lap.

I know a lot of organizations have control policies to disable the ability to make buckets public so this pattern will allow them to use your awesome solution.

I wouldn't be surprised if there are other challenges introduced via this approach we haven't ran into yet, so I like the idea of a feature flag at-least temporarily!

**Pull request merged**
